service:
  name: nest-prisma-graphql-serverless

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceInclude:
        - apollo-server-core
        - apollo-server-express

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  memorySize: 512

functions:
  main:
    handler: ./src/lambda.handler
    reservedConcurrency: 2
    events:
      - http:
          method: any
          path: /{any+}